[package]
name = "linear_state"
version = "0.1.0"
authors = ["Robert Sedlacek <rs@474.at>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
type-map = "0.3.0"
rand = "0.7.3"
smallvec = "1.4.2"
